.TH PKG 1 pkg
.SH NAME
PKG \- A All-In-One package manager wrapper for easier distro-hopping
.SH SYNOPSIS
.B pkg
<command>
.SH DESCRIPTION
.B pkg
finds the right package manager according to the Operating System and then executes the desired action on it.
.SH COMMANDS
.TP
.B c
.I clean
- configure an email account
.TP
.B h
.I help
- shows help message
.TP
.B i
.I install
- installs selected packages
.TP
.B q
.I query
- display installed packages
.TP
.B r
.I remove
- remove a selected package
.TP
.B s
.I search
- look up for a package in the available repositories
.TP
.B u
.I update
- updates repos and packages
.SH AUTHORS
Written by Rafael Marçalo originally in 2020.
.SH LICENSE
GPLv3
